--
-- PostgreSQL database dump
--
-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5
set statement_timeout = 0
;
set lock_timeout = 0
;
set idle_in_transaction_session_timeout = 0
;
set transaction_timeout = 0
;
set client_encoding = 'UTF8'
;
set standard_conforming_strings = on
;
select pg_catalog.set_config('search_path', '', false)
;
set check_function_bodies = false
;
set xmloption = content
;
set client_min_messages = warning
;
set row_security = off
;

set default_tablespace = ''
;

set default_table_access_method = heap
;

--
-- Name: careers; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.careers (
    career_id bigint NOT NULL,
    career_name character varying(255) NOT NULL,
    sheet_version_id bigint
);


--
-- Name: careers_career_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.careers ALTER COLUMN career_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.careers_career_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_subjects; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.schedule_subjects (
    schedule_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


--
-- Name: schedules; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.schedules (
    schedule_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    schedule_description character varying(255),
    user_id bigint NOT NULL
);


--
-- Name: schedules_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.schedules ALTER COLUMN schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedules_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sheet_version; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.sheet_version (
    version_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    parsed_at timestamp(6) without time zone NOT NULL,
    url character varying(255) NOT NULL
);


--
-- Name: sheet_version_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.sheet_version ALTER COLUMN version_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sheet_version_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subjects; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.subjects (
    subject_id bigint NOT NULL,
    subject_teacher_lastname character varying(255),
    aula_jueves character varying(255),
    aula_lunes character varying(255),
    aula_martes character varying(255),
    aula_miercoles character varying(255),
    aula_viernes character varying(255),
    comite_miembro1 character varying(255),
    comite_miembro2 character varying(255),
    comite_presidente character varying(255),
    subject_department character varying(255),
    subject_teacher_mail character varying(255),
    fechas_sabado_noche character varying(255),
    final1_aula character varying(255),
    final1_fecha date,
    final1_hora character varying(255),
    final1_rev_fecha date,
    final1_rev_hora character varying(255),
    final2_aula character varying(255),
    final2_fecha date,
    final2_hora character varying(255),
    final2_rev_fecha date,
    final2_rev_hora character varying(255),
    jueves character varying(255),
    lunes character varying(255),
    martes character varying(255),
    miercoles character varying(255),
    subject_name character varying(255),
    subject_teacher_name character varying(255),
    parcial1_aula character varying(255),
    parcial1_fecha date,
    parcial1_hora character varying(255),
    parcial2_aula character varying(255),
    parcial2_fecha date,
    parcial2_hora character varying(255),
    sabado character varying(255),
    subject_section character varying(255),
    subject_semester integer,
    subject_teacher_title character varying(255),
    viernes character varying(255),
    subject_career bigint
);


--
-- Name: subjects_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.subjects ALTER COLUMN subject_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id bigint NOT NULL,
    role character varying(255)
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE IF NOT EXISTS public.users (
    user_id bigint NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: careers careers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.careers
    ADD CONSTRAINT careers_pkey PRIMARY KEY (career_id);


--
-- Name: schedules schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (schedule_id);


--
-- Name: sheet_version sheet_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.sheet_version
    ADD CONSTRAINT sheet_version_pkey PRIMARY KEY (version_id);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (subject_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idxgaix2pna1ulbxhdl4kbq9yglt; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idxgaix2pna1ulbxhdl4kbq9yglt ON public.subjects USING btree (subject_name);


--
-- Name: careers fk1i91ykdx093j4yhuy84bf35nc; Type: FK CONSTRAINT; Schema: public;
-- Owner: -
--
ALTER TABLE ONLY public.careers
    ADD CONSTRAINT fk1i91ykdx093j4yhuy84bf35nc FOREIGN KEY (sheet_version_id) REFERENCES public.sheet_version(version_id);


--
-- Name: schedules fkd4y4xekwahv9boo6lc8gfl3jv; Type: FK CONSTRAINT; Schema: public;
-- Owner: -
--
ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT fkd4y4xekwahv9boo6lc8gfl3jv FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: subjects fkefbbcpxtgh4w35q5bnfcfqls5; Type: FK CONSTRAINT; Schema: public;
-- Owner: -
--
ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT fkefbbcpxtgh4w35q5bnfcfqls5 FOREIGN KEY (subject_career) REFERENCES public.careers(career_id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public;
-- Owner: -
--
ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: schedule_subjects fkofij3ckdpfw9owf8kxb1ynd7v; Type: FK CONSTRAINT; Schema:
-- public; Owner: -
--
ALTER TABLE ONLY public.schedule_subjects
    ADD CONSTRAINT fkofij3ckdpfw9owf8kxb1ynd7v FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);


--
-- Name: schedule_subjects fkrrka62dogsalj2y8yb7g67anp; Type: FK CONSTRAINT; Schema:
-- public; Owner: -
--
ALTER TABLE ONLY public.schedule_subjects
    ADD CONSTRAINT fkrrka62dogsalj2y8yb7g67anp FOREIGN KEY (schedule_id) REFERENCES public.schedules(schedule_id);


--
-- PostgreSQL database dump complete
--


